### ISSUE TITLE
org.gradle.api.GradleException

### ISSUE THREAD

**Issue by weitingyuk** [jruyi/thrift-gradle-plugin#33]
Hello, I have occur this issue after i upgrade gradle to version 8.2, and my org.jruyi.thrift version is 0.4.2, could you pls help me fix the upgrade issue? 
`Caused by: org.gradle.api.GradleException: Cannot use @TaskAction annotation on method CompileThrift.compileThrift() because interface org.gradle.api.tasks.incremental.IncrementalTaskInputs is not a valid parameter to an action method.
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore.createTaskAction(DefaultTaskClassInfoStore.java:126)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore.createTaskClassInfo(DefaultTaskClassInfoStore.java:63)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore.lambda$new$0(DefaultTaskClassInfoStore.java:43)
	at org.gradle.cache.internal.DefaultCrossBuildInMemoryCacheFactory$AbstractCrossBuildInMemoryCache.get(DefaultCrossBuildInMemoryCacheFactory.java:130)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore.getTaskClassInfo(DefaultTaskClassInfoStore.java:51)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.process(AnnotationProcessingTaskFactory.java:52)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory.create(AnnotationProcessingTaskFactory.java:48)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.createTask(DefaultTaskContainer.java:328)
	at org.gradle.api.internal.tasks.DefaultTaskContainer.access$200(DefaultTaskContainer.java:77)
	at org.gradle.api.internal.tasks.DefaultTaskContainer$2.call(DefaultTaskContainer.java:302)
	... 215 more`

**Comment by weitingyuk** [comment]
cc @szarnyasg thx~
